# Generated by Django 4.2.3 on 2023-08-13 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulos', '0002_articulos_foto_aves_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
