# Generated by Django 4.2.3 on 2023-08-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_articulos_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aves',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
