# Generated by Django 4.2.3 on 2023-08-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_aves_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aves',
            name='audio',
        ),
    ]
